# Generated by Django 2.2.5 on 2019-10-23 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='博客标题')),
                ('header', models.CharField(max_length=50, verbose_name='博客简介')),
                ('text', models.TextField(verbose_name='博客内容')),
            ],
            options={
                'verbose_name': '添加博客',
                'verbose_name_plural': '添加博客',
                'db_table': 'Blods',
            },
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='轮播图标题')),
                ('href', models.CharField(max_length=150, verbose_name='图片广告链接')),
                ('src', models.ImageField(upload_to='static/img/banner/', verbose_name='图片')),
                ('position', models.IntegerField(choices=[(1, 'new'), (2, 'old')], default=1, verbose_name='顺序')),
            ],
            options={
                'verbose_name': '代码gif',
                'verbose_name_plural': '代码gif',
                'db_table': 'Photo',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
