# Generated by Django 2.2.5 on 2019-11-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=500, verbose_name='博客标题'),
        ),
    ]
