# Generated by Django 2.2.5 on 2019-10-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=20, verbose_name='filename')),
                ('file_upload', models.FileField(upload_to='static/media')),
            ],
            options={
                'verbose_name': '上传安装包',
                'verbose_name_plural': '上传安装包',
                'db_table': 'Upload',
            },
        ),
    ]
