# Generated by Django 2.2.5 on 2019-10-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_upload_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_type',
            field=models.CharField(choices=[(0, 'Windows'), (1, 'Linux'), (2, 'Android')], default=0, max_length=20, verbose_name='安装包类型'),
        ),
    ]
