# Generated by Django 2.2.5 on 2019-10-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191024_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_type',
            field=models.IntegerField(choices=[(0, 'Windows'), (1, 'Linux'), (2, 'Android')], default=0, verbose_name='安装包类型'),
        ),
    ]
